version: '3'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    container_name: mariadb
#    volumes:
#      - db-data:/var/lib/mysql
    networks:
      - wordpress-network
    volumes:
      - ./requirements/mariadb/my.cnf:/etc/mysql/my.cnf
#    environment:
#      DB_NAME: ${DB_NAME}
#      DB_USER: ${DB_USER}
#      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
#    tty: true

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOST=${DB_HOST}
    container_name: wordpress
#   image: wordpress
    networks:
      - nginx-network
      - wordpress-network
    volumes:
      - wordpress_files:/var/www/html
      - ./requirements/wordpress/www.conf:/etc/php/8.2/fpm/pool.d/www.conf
#    environment:
#      - DB_NAME=${DB_NAME}
#      - DB_USER=${DB_USER}
#      - DB_PASSWORD=${DB_PASSWORD}

#    depends_on:
#      - mariadb
    restart: always
#    tty: true

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    ports:
      - "8080:80"
      - "4443:443"
    networks:
      - nginx-network
    depends_on:
      - wordpress
    volumes:
      - wordpress_files:/var/www/html
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/nginx/default:/etc/nginx/sites-available/default
    restart: always
#    tty: true

networks:
  nginx-network:
  wordpress-network:
# 
volumes:
    wordpress_files:
#   db-data:

#volumes:
#  wordpress_data:
#   name: wordpress
#   driver_opts:
#     type: local
#     device: ${WORDPRESS_DATA_PATH}
#  mariadb_data:
#    name: mariadb
#    driver_opts:
#      type: local
#      device: ${DB_DATA_PATH}
