version: '3'
services:
#  nginx:
#    build:
#      context: ./requirements/nginx
#      dockerfile: Dockerfile
#    container_name: nginx
#    image: nginx
#    ports:
#        - "8080:80"
#        - "4443:443"
#    tty: true

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress
    ports:
        - "8080:80"
        - "4443:443"
        - "9000:9000"
	volume:
		- "./wordpress:/var/www/html/wordpress"
    tty: true
